#!/usr/bin/env bun
/**
 * Extracts icon mappings and SVG files from the material-icon-theme npm package.
 * Run: bun scripts/sync-icons.ts
 */

import {
	cpSync,
	existsSync,
	mkdirSync,
	readFileSync,
	rmSync,
	writeFileSync,
} from "node:fs";
import { basename, join, resolve } from "node:path";

const PKG_DIR = resolve("node_modules/material-icon-theme");
const MANIFEST_PATH = join(PKG_DIR, "dist/material-icons.json");
const ICONS_SRC = join(PKG_DIR, "icons");
const ICONS_DEST = resolve("static/icons");
const GEN_PATH = resolve("src/lib/icons.gen.ts");

if (!existsSync(MANIFEST_PATH)) {
	// biome-ignore lint/suspicious/noConsole: build script
	console.error(
		"material-icon-theme not installed. Run: bun add -D material-icon-theme",
	);
	process.exit(1);
}

interface IconDef {
	iconPath: string;
}

interface LightOverrides {
	fileExtensions?: Record<string, string>;
	fileNames?: Record<string, string>;
	folderNames?: Record<string, string>;
}

interface Manifest {
	iconDefinitions: Record<string, IconDef>;
	fileExtensions: Record<string, string>;
	fileNames: Record<string, string>;
	folderNames: Record<string, string>;
	folderNamesExpanded: Record<string, string>;
	light: LightOverrides;
	file: string;
	folder: string;
	folderExpanded: string;
}

const manifest: Manifest = JSON.parse(readFileSync(MANIFEST_PATH, "utf-8"));

// Collect all referenced icon IDs
const usedIds = new Set<string>();

// Defaults
usedIds.add(manifest.file);
usedIds.add(manifest.folder);
if (manifest.folderExpanded) usedIds.add(manifest.folderExpanded);

for (const id of Object.values(manifest.fileExtensions)) usedIds.add(id);
for (const id of Object.values(manifest.fileNames)) usedIds.add(id);
for (const id of Object.values(manifest.folderNames)) usedIds.add(id);
if (manifest.folderNamesExpanded) {
	for (const id of Object.values(manifest.folderNamesExpanded)) usedIds.add(id);
}

// Also collect light override icon IDs
const light = manifest.light ?? {};
if (light.fileExtensions) {
	for (const id of Object.values(light.fileExtensions)) usedIds.add(id);
}
if (light.fileNames) {
	for (const id of Object.values(light.fileNames)) usedIds.add(id);
}
if (light.folderNames) {
	for (const id of Object.values(light.folderNames)) usedIds.add(id);
}

// Resolve icon ID → SVG filename
function resolveSvg(iconId: string): string | null {
	const def = manifest.iconDefinitions[iconId];
	if (!def) return null;
	return basename(def.iconPath);
}

// Clean and recreate dest
if (existsSync(ICONS_DEST)) rmSync(ICONS_DEST, { recursive: true });
mkdirSync(ICONS_DEST, { recursive: true });

// Copy referenced SVGs
const copiedSvgs = new Set<string>();
for (const id of usedIds) {
	const svgName = resolveSvg(id);
	if (!svgName) continue;
	if (copiedSvgs.has(svgName)) continue;
	const src = join(ICONS_SRC, svgName);
	if (existsSync(src)) {
		cpSync(src, join(ICONS_DEST, svgName));
		copiedSvgs.add(svgName);
	}
}

// Build mapping tables
function buildMap(source: Record<string, string>): Record<string, string> {
	const result: Record<string, string> = {};
	for (const [key, iconId] of Object.entries(source)) {
		const svgName = resolveSvg(iconId);
		if (svgName && copiedSvgs.has(svgName)) {
			result[key.toLowerCase()] = `/icons/${svgName}`;
		}
	}
	return result;
}

const extIcons = buildMap(manifest.fileExtensions);
const nameIcons = buildMap(manifest.fileNames);
const folderIcons = buildMap(manifest.folderNames);

// Light overrides (sparse — only icons that differ from dark)
const lightExtIcons = buildMap(light.fileExtensions ?? {});
const lightNameIcons = buildMap(light.fileNames ?? {});
const lightFolderIcons = buildMap(light.folderNames ?? {});

const defaultFile = resolveSvg(manifest.file);
const defaultFolder = resolveSvg(manifest.folder);

// Generate TypeScript
function toTs(obj: Record<string, string>): string {
	const entries = Object.entries(obj)
		.sort(([a], [b]) => a.localeCompare(b))
		.map(([k, v]) => `\t${JSON.stringify(k)}: ${JSON.stringify(v)},`)
		.join("\n");
	return `{\n${entries}\n}`;
}

const output = `// Auto-generated by scripts/sync-icons.ts — do not edit
export const EXT_ICONS: Record<string, string> = ${toTs(extIcons)};

export const NAME_ICONS: Record<string, string> = ${toTs(nameIcons)};

export const FOLDER_ICONS: Record<string, string> = ${toTs(folderIcons)};

export const LIGHT_EXT_ICONS: Record<string, string> = ${toTs(lightExtIcons)};

export const LIGHT_NAME_ICONS: Record<string, string> = ${toTs(lightNameIcons)};

export const LIGHT_FOLDER_ICONS: Record<string, string> = ${toTs(lightFolderIcons)};

export const DEFAULT_FILE = "/icons/${defaultFile}";
export const DEFAULT_FOLDER = "/icons/${defaultFolder}";
`;

writeFileSync(GEN_PATH, output);

// biome-ignore lint/suspicious/noConsole: build script
console.log(`Copied ${copiedSvgs.size} SVGs to static/icons/`);
// biome-ignore lint/suspicious/noConsole: build script
console.log(
	`Generated icons.gen.ts: ${Object.keys(extIcons).length} extensions, ${Object.keys(nameIcons).length} filenames, ${Object.keys(folderIcons).length} folders`,
);
// biome-ignore lint/suspicious/noConsole: build script
console.log(
	`Light overrides: ${Object.keys(lightExtIcons).length} extensions, ${Object.keys(lightNameIcons).length} filenames, ${Object.keys(lightFolderIcons).length} folders`,
);
